# Generated by Django 3.2.5 on 2022-08-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayPlan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='calories',
            field=models.TextField(default='None'),
        ),
    ]
