# Generated by Django 4.0.5 on 2022-08-04 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayPlan', '0002_alter_log_calories'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardio',
            name='measurement',
            field=models.CharField(choices=[('ML', 'Miles'), ('MN', 'Minutes')], default='MN', max_length=2),
        ),
        migrations.AddField(
            model_name='lift',
            name='measurement',
            field=models.CharField(choices=[('KG', 'kg'), ('LB', 'lb')], default='LB', max_length=2),
        ),
    ]
